version: '2'
services:

  php:
    image: php:7.1-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./projects/symfony/:/home/projects/symfony

  nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx/
    working_dir: /home/projects
    links:
      - php

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#      - "10009:10009"
#    links:
#      - php

  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    links:
      - php
    restart: always
##    volumes:
##      - ./data/mysql:/var/lib/mysql

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    links:
#      - mysql
